# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# For different project specify the project name in the resources block

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
  - pipeline: sourcePipeline
    source: 'iamgauravsatija.Cybria'
    trigger:
      branches:
      - master

steps:
- script: echo Triggered by source pipeline 
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project. $(resources.pipeline.sourcePipeline.pipelineName)
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
